version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    volumes:
      - "./jekyll:/app/jekyll/"
    ports:
      - 4000:4000
    command: jekyll serve
