FROM jekyll/builder

RUN apk update && apk add --update nodejs nodejs-npm
WORKDIR /app/jekyll

COPY entrypoint.sh /entrypoint
RUN sed -i 's/\r//' /entrypoint
RUN chmod +x /entrypoint

ENTRYPOINT ["/entrypoint"]
