name: Deploy Web

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and push to docker
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: josemlp91/myblog:${{ github.sha }},josemlp91/myblog:latest
    - name: Helm deploy to k8s cluster
      # uses: 'deliverybot/helm@v1'  #TODO: Replace after fix https://github.com/deliverybot/helm/issues/49
      uses: elseu/sdu-helm-deploy-action@0.0.5
      with:
        helm: helm3 
        release: 'myblog'
        namespace: 'landing'
        repository: "https://charts.bitnami.com/bitnami"
        chart: 'nginx'
        value-files: "values.yaml"
        values: |
          image:
            tag: ${{ github.sha }}
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'