name: Deploy Web

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and push to docker
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_REPOSITORY }}
        tags: ${{ github.sha }}
    - name: Helm deploy to k8s cluster
      uses: 'deliverybot/helm@v1'
      with:
        helm: helm3 
        release: 'myblog'
        namespace: 'landing'
        repository: "https://charts.bitnami.com/bitnami"
        chart: 'nginx'
        value-files: "values.yaml"
        values: |
          image:
            tag: ${{ github.sha }}
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'